# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fZ0ASlodH9Ulpw0uezo6gRZA-IOMhMvg
"""

!pip install streamlit
import fitz  # PyMuPDF
import pandas as pd
import re
import streamlit as st
import io

st.title("SDS & TDS PDF Parser 🧪")
st.write(
    "Ανέβασε τα αρχεία PDF (SDS/TDS) για να εξαχθούν αυτόματα τα συστατικά"
    " τους!"
)

def parse_sds_tds(text, filename):
  rows = []

  # 1. Trade Name από το όνομα αρχείου
  trade_name = filename.replace(".pdf", "").replace("_", " ").upper()

  # 2. INCI & CAS
  cas_matches = re.findall(
      r"(?:CAS|CAS-No\.?|CAS No\.)\s*[:\-]?\s*([0-9]{2,7}-[0-9]{2}-[0-9])",
      text,
      re.IGNORECASE,
  )
  inci_matches = re.findall(
      r"INCI(?:\s+name)?\s*[:\-]?\s*([A-Za-z\s,\/]+)", text, re.IGNORECASE
  )

  # 3. Ποσοστά (%)
  percentages = re.findall(
      r"([0-9]+(?:\.[0-9]+)?\s*-\s*[0-9]+(?:\.[0-9]+)?\s*%)", text
  )
  if not percentages:
    percentages = re.findall(r"([0-9]+(?:\.[0-9]+)?\s*%)", text)

  rows.append({
      "Trade Name": trade_name,
      "Breakdown Composition / INCI": (
          inci_matches[0].strip() if inci_matches else "Δείτε το κείμενο"
      ),
      "CAS Number": cas_matches[0] if cas_matches else "Μη διαθέσιμο",
      "Ποσοστό %": percentages[0] if percentages else "100%",
      "Impurities": "Ελέγξτε το πρωτότυπο SDS",
  })

  return rows

# Κουμπί για μεταφόρτωση PDF από τον χρήστη
uploaded_files = st.file_uploader(
    "Επέλεξε αρχεία PDF", type=["pdf"], accept_multiple_files=True
)

if uploaded_files:
  all_data = []

  for uploaded_file in uploaded_files:
    bytes_data = uploaded_file.read()
    doc = fitz.open(stream=bytes_data, filetype="pdf")
    text = "".join([page.get_text() for page in doc])
    all_data.extend(parse_sds_tds(text, uploaded_file.name))

  df = pd.DataFrame(all_data)

  st.success("Ο πίνακας δημιουργήθηκε επιτυχώς!")
  st.dataframe(df)

  # Δημιουργία κουμπιού λήψης Excel
  output = io.BytesIO()
  with pd.ExcelWriter(output, engine="openpyxl") as writer:
    df.to_excel(writer, index=False)
  excel_data = output.getvalue()

  st.download_button(
      label="📥 Λήψη Excel (structured_raw_materials.xlsx)",
      data=excel_data,
      file_name="structured_raw_materials.xlsx",
      mime=(
          "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
      ),
  )

